name: CI
on:
  push:
    paths: 
      - sub/*.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Trigger workfow
      run: |
        curl -XPOST -u ed065a4c163e2e91582c0756ab7e8f8d6ed3bbad -H "Accept: application/vnd.github.everest-preview+json"  \
        -H "Content-Type: application/json" https://api.github.com/orgs/chernleng/test_workflow/dispatches \
        --data '{"event_type": "update-api"}'
        echo invoke target workflow
