name: CI
on:
  push: 
    paths: 
      - sub/*.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Trigger workfow
      run: |
        curl -XPOST -u ${{ secrets.ACCESS_TOKEN}} -H "Accept: application/vnd.github.everest-preview+json"  \
        -H "Content-Type: application/json" https://api.github.com/chernleng/test_workflow/dispatches \
        --data '{"event_type": "update-api"}'
        echo invoke target workflow
